[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf
board_build.partitions = partitions.csv
monitor_speed = 115200
lib_deps =
    cJSON

build_unflags = -Werror
build_flags =
    -Wno-error=unused-parameter
